2024-09-07 08:11:06,780 WARNING:Privileged message content intent is missing, commands may not work as expected.
2024-09-07 08:11:06,780 INFO:logging in using static token
2024-09-07 08:11:07,428 INFO:Shard ID None has connected to Gateway (Session ID: f8702678ee619f05d890192e97d7692b).
2024-09-07 08:11:17,374 WARNING:We are being rate limited. PATCH https://discord.com/api/v10/guilds/697971426799517774/scheduled-events/1281994713859358931 responded with 429. Retrying in 2.13 seconds.
2024-09-07 08:22:57,040 WARNING:Privileged message content intent is missing, commands may not work as expected.
2024-09-07 08:22:57,040 INFO:logging in using static token
2024-09-07 08:22:57,743 INFO:Shard ID None has connected to Gateway (Session ID: 166b6f7ead356c30b7d65be08e5ee227).
2024-09-07 08:23:07,585 WARNING:We are being rate limited. PATCH https://discord.com/api/v10/guilds/697971426799517774/scheduled-events/1281994713859358931 responded with 429. Retrying in 1.72 seconds.
2024-09-07 10:32:20,080 ERROR:Attempting a reconnect in 1.74s
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiohttp\connector.py", line 1173, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiohttp\connector.py", line 884, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 861, in getaddrinfo
    return await self.run_in_executor(
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\client.py", line 664, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 479, in wait_for
    return fut.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\gateway.py", line 374, in from_client
    socket = await client.http.ws_connect(str(url))
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\http.py", line 550, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiohttp\client.py", line 832, in _ws_connect
    resp = await self.request(
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiohttp\client.py", line 578, in _request
    conn = await self._connector.connect(
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiohttp\connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [getaddrinfo failed]
2024-09-07 10:32:22,040 INFO:Shard ID None session has been invalidated.
2024-09-07 10:32:27,423 INFO:Shard ID None has connected to Gateway (Session ID: 468183fd2ed1c21eafc6193fd519f7fc).
2024-09-07 12:38:24,809 INFO:Shard ID None has successfully RESUMED session 468183fd2ed1c21eafc6193fd519f7fc.
2024-09-07 16:32:05,095 INFO:Shard ID None has successfully RESUMED session 468183fd2ed1c21eafc6193fd519f7fc.
2024-09-07 16:49:30,247 WARNING:Shard ID None has stopped responding to the gateway. Closing and restarting.
2024-09-07 16:49:38,009 INFO:Shard ID None session has been invalidated.
2024-09-07 16:49:43,429 INFO:Shard ID None has connected to Gateway (Session ID: 22cd8f7e7fe4685019746fba99928d74).
2024-09-07 17:55:49,026 WARNING:Privileged message content intent is missing, commands may not work as expected.
2024-09-07 17:55:49,026 INFO:logging in using static token
2024-09-07 17:55:50,030 INFO:Shard ID None has connected to Gateway (Session ID: ee444a563fe3838f9bc3d46c5448a5b7).
